{
  "comments": [
    {
      "key": {
        "uuid": "f71c0b4a_be0c1ce2",
        "filename": "dump/dump_collect.cpp",
        "patchSetId": 5
      },
      "lineNbr": 191,
      "author": {
        "id": 1000089
      },
      "writtenOn": "2021-10-28T04:07:31Z",
      "side": 1,
      "message": "duplicate traces, pdbg.init will already log some traces when throwing exception,,, suggestion",
      "range": {
        "startLine": 185,
        "startChar": 0,
        "endLine": 191,
        "endChar": 5
      },
      "revId": "39208c4714354c36fb7847cda351fbb15f87fa3d",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "c2d5fc82_3d52207a",
        "filename": "dump/dump_collect.cpp",
        "patchSetId": 5
      },
      "lineNbr": 217,
      "author": {
        "id": 1000089
      },
      "writtenOn": "2021-10-28T04:07:31Z",
      "side": 1,
      "message": "assume isPrimaryProc also logs error which is sufficient, duplicate traces , suggestion",
      "range": {
        "startLine": 209,
        "startChar": 0,
        "endLine": 217,
        "endChar": 13
      },
      "revId": "39208c4714354c36fb7847cda351fbb15f87fa3d",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4",
      "unresolved": true
    }
  ]
}