{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "8de8a2d2_481b8abe",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 10
      },
      "lineNbr": 0,
      "author": {
        "id": 1001591
      },
      "writtenOn": "2022-12-22T07:51:47Z",
      "side": 1,
      "message": "A suggestion and an observation",
      "revId": "ce0597fe9deafefbb7815bf8fba9e8d6e22c4230",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "d236ef5f_3ed2ef46",
        "filename": "dump/dump_utils.cpp",
        "patchSetId": 10
      },
      "lineNbr": 73,
      "author": {
        "id": 1001591
      },
      "writtenOn": "2022-12-22T07:51:47Z",
      "side": 1,
      "message": "If dumpPath.parent_path() returns std::filesystem::path then use auto elogPath \u003d dumpPath.parent_path(); otherwise use static_cast to cast properly",
      "revId": "ce0597fe9deafefbb7815bf8fba9e8d6e22c4230",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "4f3ed1f1_b1fa6973",
        "filename": "dump/dump_utils.cpp",
        "patchSetId": 10
      },
      "lineNbr": 73,
      "author": {
        "id": 1000084
      },
      "writtenOn": "2022-12-27T14:31:02Z",
      "side": 1,
      "message": "I didnt get the problem with this statemnent",
      "parentUuid": "d236ef5f_3ed2ef46",
      "revId": "ce0597fe9deafefbb7815bf8fba9e8d6e22c4230",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "5d86459a_6c48ce78",
        "filename": "dump/dump_utils.cpp",
        "patchSetId": 10
      },
      "lineNbr": 98,
      "author": {
        "id": 1001591
      },
      "writtenOn": "2022-12-22T07:51:47Z",
      "side": 1,
      "message": "We are using two different try-catch blocks in this function where one is required to stop collecting the dumps if an exception is thrown (at line no 66) and at line not 98 we can continue the dump collection. Can we use on try and two catch blocks where the throw one will be the first one catch block followed by the second one at line 98?",
      "revId": "ce0597fe9deafefbb7815bf8fba9e8d6e22c4230",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "8fa1ce09_2a3e753d",
        "filename": "dump/dump_utils.cpp",
        "patchSetId": 10
      },
      "lineNbr": 98,
      "author": {
        "id": 1000084
      },
      "writtenOn": "2022-12-27T14:31:02Z",
      "side": 1,
      "message": "Done",
      "parentUuid": "5d86459a_6c48ce78",
      "revId": "ce0597fe9deafefbb7815bf8fba9e8d6e22c4230",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    }
  ]
}